name: release

on:
  push:
    branches:
      - v*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'

      - name: Build
        env:
          gh_ci_key: ${{ secrets.GH_CI_KEY }}
        run: |
          mkdir -p tmp
          go build -o tmp ./...
          ./tmp/ziti-ci generate-build-info cmd/build_info.go cmd
          go build -o tmp ./...
          echo "ZITI_CI_VERSION=$(./tmp/ziti-ci get-version -q)" >> $GITHUB_ENV
          ./tmp/ziti-ci configure-git
          ./tmp/ziti-ci tag -v -f version

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.ZITI_CI_VERSION }}
          tag_name: ${{ env.ZITI_CI_VERSION }}
          files: ./tmp/ziti-ci/ziti-ci
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          # token: ${{ secrets.GITHUB_TOKEN }} # this Action defaults to github.token
